name: Spring Boot Github Action Workflow
on: [push, workflow_dispatch]
permissions:
  contents: read
  checks: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checking Out Code
          uses: actions/checkout@v4
        - name: Setting Up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Setting Up Gradle 8.5
          uses: gradle/gradle-build-action@v2
          with:
              gradle-version: 8.5
        - name: Compiling
          run: ./gradlew compileJava compileTestJava compileIntegrationTestJava
        - name: Running Unit Tests
          run: ./gradlew test
        - name: Running Integration Tests
          run: ./gradlew integrationTest
        - name: Code Coverage Verification
          run: ./gradlew jacocoTestCoverageVerification
        - name: Check Code Style
          run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest
        - uses: jwgmeligmeyling/checkstyle-github-action@master
          with:
            path: '**/build/reports/checkstyle/main.xml'
        - name: Running Spotbugs
          run: ./gradlew spotbugsMain spotbugsTest spotbugsIntegrationTest
        - uses: jwgmeligmeyling/spotbugs-github-action@master
          with:
            path: '**/build/reports/spotbugs/spotbugs.xml'
        - name: Running PMD
          run: ./gradlew pmdMain pmdTest pmdIntegrationTest
        - uses: jwgmeligmeyling/pmd-github-action@master
          with:
            path: '**/build/reports/pmd/main.xml'
        - name: Publish Unit Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: '**/build/test-results/test/TEST-*.xml'
            check_name: 'JUnit Test Report'
        - name: Publish Integration Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: '**/build/test-results/integrationTest/TEST-*.xml'
            check_name: 'JUnit Integration Test Report'



#        - name: Upload Build Reports
#          uses: actions/upload-artifact@v3
#          if: always()
#          with:
#            name: build-reports
#            path: build/reports/

