name: Spring Boot Github Action Workflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Set Up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Set Up Gradle 8.5
          uses: gradle/gradle-build-action@v2
          with:
              gradle-version: 8.5
        - name: Execute Gradle Build
          run: ./gradlew build

