name: Spring Boot Github Action Workflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checking Out Code
          uses: actions/checkout@v4
        - name: Setting Up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Setting Up Gradle 8.5
          uses: gradle/gradle-build-action@v2
          with:
              gradle-version: 8.5
        - name: Compiling
          run: ./gradlew compileJava compileTestJava compileIntegrationTestJava
        - name: Running Unit Tests
          run: ./gradlew test
        - name: Running Integration Tests
          run: ./gradlew integrationTest
        - name: Code Coverage Verification
          run: ./gradlew jacocoTestCoverageVerification
#        - name: Upload Build Reports
#          uses: actions/upload-artifact@v3
#          if: always()
#          with:
#            name: build-reports
#            path: build/reports/

